# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0003_ntwrk_ntwrk_vlanid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtm',
            name='vm_os',
        ),
        migrations.AddField(
            model_name='ntwrk',
            name='vms',
            field=models.ManyToManyField(to='pyvmomi.Virtm'),
        ),
        migrations.AddField(
            model_name='virtm',
            name='vm_dns',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtm',
            name='vm_ip',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtm',
            name='vm_memory',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtm',
            name='vm_state',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
