# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0004_auto_20190115_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=200)),
                ('host_fullname', models.CharField(max_length=100)),
                ('host_ostype', models.CharField(max_length=100)),
                ('host_productlineid', models.CharField(max_length=100)),
                ('host_apiversion', models.CharField(max_length=50)),
                ('host_name', models.CharField(max_length=100)),
                ('host_totalcpu', models.PositiveIntegerField()),
                ('host_numcpucores', models.PositiveIntegerField()),
                ('host_numcputhreads', models.PositiveIntegerField()),
                ('host_effectivecpu', models.PositiveIntegerField()),
                ('host_totalmemory', models.PositiveIntegerField()),
                ('host_effectivememory', models.PositiveIntegerField()),
                ('host_overallstatus', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='ntwrk',
            name='vms',
        ),
        migrations.DeleteModel(
            name='Ntwrk',
        ),
        migrations.DeleteModel(
            name='Virtm',
        ),
    ]
