# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0005_auto_20190122_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datastore', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('freespace', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyvmomi.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Virtualswitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mtu', models.PositiveIntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyvmomi.Host')),
            ],
        ),
    ]
