# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0006_datastore_virtualswitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Virtualmachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numcpu', models.PositiveIntegerField()),
                ('numcorepersocket', models.PositiveIntegerField()),
                ('memorymb', models.PositiveIntegerField()),
                ('datastore', models.ManyToManyField(to='pyvmomi.Datastore')),
            ],
        ),
    ]
