# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0007_virtualmachine'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='guestFullName',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='guestState',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='hostName',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='ipAddress',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='toolsStatus',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
