# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0008_auto_20190126_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discpath', models.CharField(default=None, max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('freespace', models.PositiveIntegerField()),
                ('virtualmachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyvmomi.Virtualmachine')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iproute', models.CharField(default=None, max_length=100)),
                ('gateway', models.CharField(default=None, max_length=100)),
                ('virtualmachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyvmomi.Virtualmachine')),
            ],
        ),
    ]
