# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0010_auto_20190127_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='disk',
            name='freespace',
            field=models.BigIntegerField(),
        ),
    ]
