# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0012_auto_20190127_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physicalnick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(default='N/A', max_length=100)),
                ('driver', models.CharField(default='N/A', max_length=100)),
                ('mac', models.CharField(default='N/A', max_length=100)),
                ('speedmb', models.CharField(default='N/A', max_length=100)),
                ('duplex', models.CharField(default='N/A', max_length=100)),
                ('virtualswitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyvmomi.Virtualswitch')),
            ],
        ),
        migrations.CreateModel(
            name='Portgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('vlanid', models.PositiveIntegerField()),
                ('device', models.CharField(default='N/A', max_length=100)),
                ('portgroup', models.CharField(default='N/A', max_length=100)),
                ('dhcp', models.CharField(default='N/A', max_length=100)),
                ('ipaddress', models.CharField(default='N/A', max_length=100)),
                ('subnetmask', models.CharField(default='N/A', max_length=100)),
                ('mac', models.CharField(default='N/A', max_length=100)),
                ('virtualswitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyvmomi.Virtualswitch')),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='gateway',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='iproute',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
