# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0013_auto_20190127_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portgroup',
            name='portgroup',
        ),
    ]
