# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0014_remove_portgroup_portgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portgroup',
            name='dhcp',
            field=models.BooleanField(),
        ),
    ]
