# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0015_auto_20190127_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portgroup',
            name='dhcp',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
