# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0016_auto_20190127_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed', models.BigIntegerField(default=0)),
                ('uncommitted', models.BigIntegerField(default=0)),
                ('unshared', models.BigIntegerField(default=0)),
                ('datastore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyvmomi.Datastore')),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='host_apiversion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_effectivecpu',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_effectivememory',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_fullname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_ip',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_numcpucores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_numcputhreads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_ostype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_overallstatus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_productlineid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_totalcpu',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_totalmemory',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='memorymb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='numcorepersocket',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='numcpu',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='virtualswitch',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storage',
            name='virtualmachine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyvmomi.Virtualmachine'),
        ),
    ]
