# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0017_auto_20190206_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='datastore'
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='datastore',
            field=models.ManyToManyField(through='pyvmomi.Storage', to='pyvmomi.Datastore'),
        ),
    ]
