# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0018_auto_20190206_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='datastore',
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pyvmomi.Host'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage',
            name='datastore',
            field=models.CharField(default='N/A', max_length=150),
        ),
    ]
