# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0019_auto_20190208_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disk',
            old_name='discpath',
            new_name='diskpath',
        ),
    ]
