# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvmomi', '0020_auto_20190208_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_check',
            field=models.BooleanField(default=True),
        ),
    ]
